### ISSUE TITLE
Guide on how to create a space?

### ISSUE THREAD

**Issue by hathawayj** [vsls-contrib/spaces#128]
This looks fantastic.  The directions are very clear on how to join a space.  Can you provide a link or direction on how to create a new space?

**Comment by hathawayj** [comment]
It looks like there hasn't been a push to this repo for 2-months.  Will this continue to be maintained?  How often do you check issues?

**Comment by lostintangent** [comment]
@hathawayj Hey! Apologies for the late reply. Currently, the way to create a space is to simply be the first person to join it. The first person to join a space becomes the owner of that space, and can therefore administrate it.

I'd love to hear more about how you're thinking of using Spaces, and how we might be able to improve it further 👍

**Comment by hathawayj** [comment]
@lostintangent, thanks for the response. From your note and the readme, it looks like you are assuming that I click the `+` in the Space or on `Join a space...` then I would be able to type my own space name and then be the first to join?

![](https://user-images.githubusercontent.com/116461/64935372-c00ca100-d805-11e9-8393-ee6c87e2fce4.png)

However, I can't even get spaces to join any of the spaces that show up.  I see four spaces, and then when I click on them, nothing happens.  Using the link at the top of your readme doesn't work either.

![Screen Shot 2020-09-28 at 10 04 31 AM](https://user-images.githubusercontent.com/6199492/94457934-7d98d680-0172-11eb-94e5-beb8537a5b05.png)

I am on a MacBook Pro 2019 and have been using VS Code for the last year.  I have used Live Share a few times as well.

### Use Case

I would love to use this with my data science programming class as we are heavily using VS Code in class.  This tool seems like a nice technology for remote labs, office hours, and class.  That is if I can get it to work.

Thanks.

**Comment by arjun27** [comment]
Thanks for reporting this and sharing your use-case, @hathawayj.

I believe you're running into an issue I fixed with https://github.com/vsls-contrib/spaces/commit/a8d91359b12e092f18f85b1ddaf6139dafd0d2e0 last night. Some of the underlying primitives (authentication, chat) that Spaces relies upon have evolved significantly over the last year, causing a few more things to break. We will be prioritizing these fixes over the week. I'll keep this issue open till we push a new build to the Marketplace.

**Comment by hathawayj** [comment]
I am still having issues with this.  I have tried to `join a space` or create one and nothing happens in both cases. I have tried on a windows machine logged in through a Microsoft account and on a mac machine logged in through GitHub.  Still doesn't do anything.  Any progress?

**Comment by hwpplayer1** [comment]
> I am still having issues with this. I have tried to `join a space` or create one and nothing happens in both cases. I have tried on a windows machine logged in through a Microsoft account and on a mac machine logged in through GitHub. Still doesn't do anything. Any progress?

Do you have any further progression ?
